import Navbar from '../components/Navbar'
import Footer from '../components/Footer'
import Head from 'next/head'
import styles from './page.module.css'

// export const metadata = {
//   title: 'PokeNext',
//   description: 'Generated by Next.js',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <>
        <html lang="pt-br">
          <Head>
              <link rel="shortcut icon" href="../../public/images/pokeball.png" type="image/x-icon" />
              <title>Home</title>
          </Head>
          <body className={styles.body}>
            <Navbar />
            <main className={styles.main_conteiner}>{children}</main>
            <Footer />
          </body>
        </html>
    </>
  )
}
