import styles from "../styles/Home.module.css"

import Image from 'next/image'

import Card from '../components/Card'

export const metadata = {
  title: 'PokeNext',
  description: 'Generated by Next.js',
}

const maxPokemons = 251;
const api = 'https://pokeapi.co/api/v2/pokemon';

async function fetchPokemons() {
  const res = await fetch(`${api}/?limit=${maxPokemons}`);
  const data = await res.json();

  // Add Pokémon index
  data.results.forEach((item, index) => {
    item.id = index + 1;
  });

  return data.results;
}

export default async function Home() {
  const pokemons = await fetchPokemons();

  return (
    <>
      <div className={styles.pkm_container}>
        <div className={styles.title_container}>
          <h1 className={styles.title}>Poké<span>Next</span></h1>
          <Image src="/images/pokeball.png" width="50" height="50"/>
        </div>
        <div className={styles.pkm_content}>
          {pokemons.map((pokemon) => (
            <Card key={pokemon.id} pokemon={pokemon} />
          ))}
        </div>
      </div>
    </>
  );
}
